### ISSUE TITLE
[Bug]: LTO option prevents metadata generation

### ISSUE THREAD

**Issue by SadakazuNagao** [sony/esstra#18]
### Mandatory confirmtion

- [x] follow this project's [Code of Conduct](https://github.com/sony/esstra/blob/main/CODE_OF_CONDUCT.md).
- [x] follow this project's [Contributing Guidelines](https://github.com/sony/esstra/blob/main/CONTRIBUTING.md).
- [x] have checked the [issue list](https://github.com/sony/esstra/issues), and confirm that a similar issue has not been reported before.

### Description

- **Description**: When using the LTO option (`-flto`) with `gcc`/`g++`, the generated binaries do not contain the expected metadata.
- **Workaround**: Remove the LTO option.

### Version of ESSTRA

v0.1.0

### Environment

Ubuntu 22.04 and Ubuntu 24.04 on an x86\_64 PC 

### Steps to reproduce

In sample/hello/, compile hello.c with the '-flto' option and run 'esstra.py show':

```shell
$ gcc -flto -fplugin=/<path_to_plugin>/esstracore.so hello.c -o hello
$ esstra.py show hello
#
# BinaryFileName: hello
# BinaryPath: /home/snagao/esstra/samples/hello/hello
#
Headers:
  ToolName: ESSTRA Core
  ToolVersion: 0.1.1-develop
  DataFormatVersion: 0.1.0-develop
  InputFileNames:
  - /tmp/cczAjq52.ltrans0.o
SourceFiles: {}
$
```

The result contains an incorrect value for `SourceFiles:` as shown above.

### Additional context

[Annobin](https://sourceware.org/annobin/), a binary annotation and analysis package, seems to have encountered a similar issue, and some steps appear to have been taken to resolve it.

* https://sourceware.org/cgit/annobin/tree/gcc-plugin/annobin.cc#n206
* https://sourceware.org/cgit/annobin/tree/gcc-plugin/annobin.cc#n2564

**Comment by SadakazuNagao** [comment]
We compiled the code in [`sample/hello2/`](https://github.com/sony/esstra/tree/main/samples/hello2) using ESSTRA Core with the `-flto` (Link Time Optimization) option. The compilation steps were:

```bash
$ gcc -flto -fplugin=/.../esstracore.so -c hello_main.c
$ gcc -flto -fplugin=/.../esstracore.so -c hello_sub.c
$ gcc -flto -fplugin=/.../esstracore.so hello_main.o hello_sub.o -o hello2
```

After compilation, we checked the metadata embedded in each binary. The results are as follows:

### `hello_main.o`

```yaml
#
# BinaryFileName: hello_main.o
# BinaryPath: /home/snagao/esstra/samples/hello2/hello_main.o
#
Headers:
  ToolName: ESSTRA Core
  ToolVersion: 0.3.0-develop
  DataFormatVersion: 0.1.0
  InputFileNames:
  - hello_main.c
SourceFiles:
- Directory: /home/snagao/esstra/samples/hello2
  Files:
  - File: hello_main.c
    SHA1: f7f5c447d68fd9685594a31cb10c8d8b1dd5ebd6
  - File: hello_sub.h
    SHA1: 3e5b3ed1aed966c0e0c183eac8fe6ea02dfa62a0
- Directory: /usr/include
  Files:
  - File: stdc-predef.h
    SHA1: 2fef05d80514ca0be77efec90bda051cf87d771f
```

### `hello_sub.o`

```yaml
#
# BinaryFileName: hello_sub.o
# BinaryPath: /home/snagao/esstra/samples/hello2/hello_sub.o
#
Headers:
  ToolName: ESSTRA Core
  ToolVersion: 0.3.0-develop
  DataFormatVersion: 0.1.0
  InputFileNames:
  - hello_sub.c
SourceFiles:
- Directory: /home/snagao/esstra/samples/hello2
  Files:
  - File: hello_sub.c
    SHA1: cfb72998ae0242237fa42c8bcf61ee5887137392
- Directory: /usr/include
  Files:
  - File: features-time64.h
    SHA1: 57c3c8093c3af70e5851f6d498600e2f6e24fdeb
  - File: features.h
    SHA1: d8725bb98129d6d70ddcbf010021c2841db783f7
  - File: stdc-predef.h
    SHA1: 2fef05d80514ca0be77efec90bda051cf87d771f
  - File: stdio.h
    SHA1: c7181b48c4194cd122024971527aab4056baf600
- Directory: /usr/include/x86_64-linux-gnu/bits
  Files:
  - File: floatn-common.h
    SHA1: 3f37104123a2e6180621331c1da87125808e47bd
  - File: floatn.h
    SHA1: 806b759ab6894a09a3b3a422eec5f2414ba7dab7
  - File: libc-header-start.h
    SHA1: e0a400c194cd3962a342a6504a441920163b799c
      :
   (truncated)
```
### `hello2` (final binary)

```yaml
#
# BinaryFileName: ./hello2
# BinaryPath: /home/snagao/esstra/samples/hello2/hello2
#
Headers:
  ToolName: ESSTRA Core
  ToolVersion: 0.3.0-develop
  DataFormatVersion: 0.1.0
  InputFileNames:
  - /tmp/ccNiHWdM.ltrans0.o
SourceFiles: []
```

### Observation

The final binary `hello2` does not contain the expected metadata. It only refers to a temporary object file generated during LTO (`/tmp/ccNiHWdM.ltrans0.o`) and does not include any source file information.

### Analysis

This behavior is likely caused by the nature of LTO (Link Time Optimization). During the link phase, the compiler performs various optimizations and generates temporary object files. As a result, the normal linking process is replaced. This leads to incomplete metadata in the final binary.
